# Generated by Django 4.2.4 on 2023-08-17 19:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('age_limit', models.CharField(choices=[('All', 'Padrão'), ('kids', 'Infantil')], max_length=10)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('classification', models.CharField(choices=[('Series', 'Séries'), ('Movies', 'Filmes'), ('Documentaries', 'Documentários'), ('Animations', 'Animações'), ('Reality Shows', 'Reality Shows '), ('Cooking Shows', 'Programas de Culinária'), ('Stand up', 'Stand up'), ('TV Shows', 'Programas de TV'), ('Anime', 'Animes'), ("Kids' Programs", 'Programas infantis')], max_length=50)),
                ('genre', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images')),
                ('age_limit', models.CharField(choices=[('All', 'Padrão'), ('kids', 'Infantil')], max_length=10)),
                ('video', models.ManyToManyField(to='netflixapp.video')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('profiles', models.ManyToManyField(blank=True, to='netflixapp.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
