# Generated by Django 4.2.4 on 2023-08-17 20:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(choices=[('All', 'Padrão'), ('kids', 'Infantil')], max_length=10, verbose_name='faixa etária'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='classification',
            field=models.CharField(choices=[('Series', 'Séries'), ('Movies', 'Filmes'), ('Documentaries', 'Documentários'), ('Animations', 'Animações'), ('Reality Shows', 'Reality Shows '), ('Cooking Shows', 'Programas de Culinária'), ('Stand up', 'Stand up'), ('TV Shows', 'Programas de TV'), ('Anime', 'Animes'), ("Kids' Programs", 'Programas infantis')], max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=250, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Capa'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='id'),
        ),
    ]
