# Generated by Django 4.2.6 on 2023-12-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0003_rename_genretwo_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Gerente'),
        ),
    ]
