# Generated by Django 4.2.6 on 2023-12-19 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0004_profile_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_manager',
        ),
    ]
