# Generated by Django 4.2.4 on 2023-08-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0004_alter_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
