# Generated by Django 4.2.4 on 2023-08-18 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0005_alter_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(choices=[('All', 'Adulto'), ('kids', 'Infantil')], max_length=10, verbose_name='faixa etária'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_limit',
            field=models.CharField(choices=[('All', 'Adulto'), ('kids', 'Infantil')], max_length=10, verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='files', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
