# Generated by Django 4.2.4 on 2023-08-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0006_alter_movie_age_limit_alter_profile_age_limit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
