# Generated by Django 4.2.6 on 2023-12-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_managers_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(choices=[(True, 'SIM'), (False, 'NAO')], default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(choices=[(True, 'SIM'), (False, 'NAO')], default=False),
        ),
    ]
